# Generated by Django 4.0.4 on 2022-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=10, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.BooleanField(blank=True, choices=[(0, '女'), (1, '男')], default='', verbose_name='性别')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, max_length=11, verbose_name='联系电话')),
                ('register_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
        ),
    ]
